import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, FileText, MessageCircle, PackageCheck, Settings2, ShieldCheck, Wrench } from "lucide-react";
import { products } from "@/data/site";
import { ClientLogos } from "@/components/client-logos";

export const metadata = {
  alternates: { canonical: "/" },
};

const productImages = ["/images/home-high-speed-roll-up.webp", "/images/catalog-high-speed-spiral.webp", "/images/industrial-sectional-door.webp", "/images/home-dock-leveler.webp"];
const productImagePositions = ["50% 58%", "50% 50%", "50% 50%", "54% 42%"];
const productLinks: Record<string, string> = {
  "high-speed-roll-up-door": "/products/high-speed-roll-up-door",
  "high-speed-spiral-door": "/products/high-speed-spiral-door",
  "industrial-sectional-door": "/products/industrial-sectional-door",
  "hydraulic-dock-leveler": "/products/hydraulic-dock-leveler",
};
const applicationCards = [
  { title: "Manufacturing Lines", image: "/images/hero-industrial-door.jpg", copy: "Rapid, safe separation for automated equipment and high-frequency production flow." },
  { title: "Logistics & Warehousing", image: "/images/logistics-door.jpg", copy: "Large-opening access designed around vehicles, traffic and loading efficiency." },
  { title: "Food & Clean Areas", image: "/images/cleanroom-door.jpg", copy: "Controlled access with practical sealing, hygiene and pressure-management options." },
];
const latestNews = [
  { slug: "new-generation-high-speed-roll-up-door", category: "Product News", date: "August 19, 2026", title: "New-Generation High-Speed Roll-Up Door for Busy Production Areas", excerpt: "Explore the upgraded drive, safety sensing and sealing details developed for high-frequency industrial traffic.", image: "/images/new-generation-yellow-high-speed-doors.jpg" },
  { slug: "control-dust-and-airflow-between-production-zones", category: "Solutions", date: "August 18, 2026", title: "How to Control Dust and Airflow Between Production Zones", excerpt: "A practical rapid-door solution for facilities that need efficient traffic flow and reliable environmental separation.", image: "/images/hero-industrial-door.jpg" },
  { slug: "high-speed-roll-up-door-food-material-access", category: "Solutions", date: "August 17, 2026", title: "High-Speed Roll-Up Doors for Food Material Access", excerpt: "Reduce dust transfer, shorten waiting time and improve raw-material traffic in food production areas.", image: "/images/cleanroom-door.jpg" },
];

export default function Home() {
  return <div className="reference-home">
    <section className="reference-hero"><Image src="/images/hero-industrial-door.jpg" alt="SEPPES high speed doors in an industrial production facility" fill priority sizes="100vw" className="reference-hero__image" /><div className="reference-hero__shade" /><div className="container reference-hero__inner"><div className="reference-hero__content"><p className="reference-eyebrow">SEPPES Industrial Doors</p><h1>Industrial Door Systems for Modern Facilities</h1><p>Compare high-speed doors, sectional doors and loading dock equipment, then discuss your opening, traffic, environment and control requirements with our B2B team.</p><div className="reference-actions"><Link className="reference-button reference-button--red" href="/contact">Request a Quote <ArrowRight size={18} /></Link><a className="reference-button reference-button--ghost" href="https://wa.me/8617798578460" target="_blank" rel="noreferrer"><MessageCircle size={18} /> Discuss on WhatsApp</a></div></div></div><a className="reference-scroll" href="#product-families"><span>Explore</span><i /></a></section>
    <section className="reference-trust"><div className="container reference-split-heading"><div><p className="reference-eyebrow blue">Company facts</p><h2>Manufacturing You Can Verify</h2></div><div className="reference-copy"><strong>SEPPES has engineered industrial entrance systems in Suzhou since 2011.</strong><p>Backed by a 20,000+ m² manufacturing base, our products support customers in more than 90 countries with project review, customized manufacturing, export coordination and technical documentation.</p></div></div><div className="container reference-facts"><div><span>Experience</span><strong>Since 2011</strong></div><div><span>Manufacturing</span><strong>20,000+ m² facility</strong></div><div><span>Global reach</span><strong>90+ countries</strong></div><div><span>Customer base</span><strong>7,600+ companies</strong></div></div></section>
    <section className="reference-section" id="product-families"><div className="container"><div className="reference-split-heading"><div><p className="reference-eyebrow blue">Explore our products</p><h2>Industrial Door Product Families</h2></div><div className="reference-copy"><strong>Start with the operating challenge, not just the door name.</strong><p>Compare access speed, opening size, environmental separation, traffic type and loading requirements before choosing a configuration.</p></div></div><div className="reference-product-grid">{products.map((product, index) => <Link className="reference-product-card" href={productLinks[product.slug] ?? `/products#${product.slug}`} key={product.slug}><Image src={productImages[index]} alt={`${product.name} installed by SEPPES`} fill sizes="(min-width: 900px) 50vw, 100vw" style={{ objectPosition: productImagePositions[index] }} /><span className="reference-card-shade" /><div className="reference-product-card__content"><div><p>{product.category}</p><h3>{product.name}</h3><span>{product.description}</span></div><footer><b>0{index + 1}</b><em>Explore product <ArrowUpRight size={19} /></em></footer></div></Link>)}</div></div></section>
    <section className="reference-guide"><div className="container"><div className="reference-guide__head"><p className="reference-eyebrow">Select by project requirements</p><h2>Which Industrial Door Is Right for Your Opening?</h2><p>Use these four questions as a practical starting point. A final recommendation should still be reviewed against the site conditions and technical requirements.</p></div><div className="reference-guide__grid"><div><b>01</b><h3>How often does it open?</h3><p>Continuous traffic generally benefits from fast cycle times and automated activation.</p></div><div><b>02</b><h3>What must be controlled?</h3><p>Temperature, dust, hygiene, wind and pressure all influence the door construction.</p></div><div><b>03</b><h3>How large is the opening?</h3><p>Opening dimensions, headroom and side room narrow the appropriate product family.</p></div><div><b>04</b><h3>Who or what passes through?</h3><p>Pedestrians, forklifts, AGVs and trucks require different safety and control strategies.</p></div></div><Link className="reference-button reference-button--red" href="/contact">Discuss your application <ArrowRight size={18} /></Link></div></section>
    <section className="reference-blog"><div className="container"><div className="reference-split-heading"><div><p className="reference-eyebrow blue">Latest from SEPPES</p><h2>Product News & Industrial Insights</h2></div><div className="reference-copy"><strong>Fresh knowledge for better project decisions.</strong><p>Follow our latest product updates, application solutions and project stories from industrial facilities worldwide.</p><Link className="reference-blog__all" href="/source/blog">View all news <ArrowUpRight size={17} /></Link></div></div><div className="reference-blog__grid">{latestNews.map((post) => <Link className="reference-blog__card" href={`/source/blog/${post.slug}`} key={post.title}><div className="reference-blog__image"><Image src={post.image} alt={post.title} fill sizes="(min-width: 900px) 33vw, 100vw" /></div><div className="reference-blog__body"><div className="reference-blog__meta"><span>{post.category}</span><time>{post.date}</time></div><h3>{post.title}</h3><p>{post.excerpt}</p><em>Read article <ArrowRight size={16} /></em></div></Link>)}</div></div></section>
    <section className="reference-section" id="solutions"><div className="container"><div className="reference-split-heading"><div><p className="reference-eyebrow blue">Industrial solutions</p><h2>Designed Around the Operating Environment</h2></div><div className="reference-copy"><strong>Door performance depends on where and how the opening is used.</strong><p>Our team reviews workflow, environmental separation, safety devices and control interfaces before confirming the solution.</p></div></div><div className="reference-application-grid">{applicationCards.map((item, index) => <article key={item.title}><div><Image src={item.image} alt={item.title} fill sizes="(min-width: 900px) 33vw, 100vw" /></div><span>0{index + 1}</span><h3>{item.title}</h3><p>{item.copy}</p></article>)}</div></div></section>
    <section className="reference-source"><div className="container reference-source__grid"><div className="reference-source__image"><Image src="/images/home-factory-exterior.webp" alt="Exterior of the SEPPES industrial door factory in Suzhou" fill sizes="(min-width: 900px) 50vw, 100vw" style={{ objectPosition: "53% 58%" }} /></div><div><p className="reference-eyebrow">Source manufacturer</p><h2>From Project Review to Export Delivery</h2><p>Work directly with a manufacturing team offering nearly 70 product configurations, 30+ recognized certifications and coordinated support from opening review through export delivery.</p><ul><li><Check /> Application and opening review</li><li><Check /> OEM and ODM configuration</li><li><Check /> Quality inspection and export packaging</li><li><Check /> Installation documents and remote support</li></ul><Link className="reference-text-link light" href="/about">See our manufacturing approach <ArrowUpRight size={17} /></Link></div></div></section>
    <section className="reference-section reference-support" id="project-support"><div className="container"><div className="reference-split-heading"><div><p className="reference-eyebrow blue">B2B project support</p><h2>Support Beyond the Door Panel</h2></div><div className="reference-copy"><strong>A complete industrial entrance is a coordinated system.</strong><p>We help buyers clarify the supply scope before production and prepare the information needed for local installation.</p></div></div><div className="reference-support__grid"><article><Settings2 /><b>01</b><h3>Configuration Support</h3><p>Opening review, product selection, motor and control matching.</p></article><article><ShieldCheck /><b>02</b><h3>Safety & Controls</h3><p>Sensors, activation methods and access-control interface planning.</p></article><article><FileText /><b>03</b><h3>Documentation</h3><p>Technical drawings, wiring information and installation guidance.</p></article><article><Wrench /><b>04</b><h3>After-Sales Support</h3><p>Remote assistance and replacement component coordination.</p></article></div><div className="reference-requirements"><div><p className="reference-eyebrow blue">Project information</p><h3>Ready to Discuss Your Opening?</h3><p>Send the width, height, quantity, application, project location and any available drawings or photos.</p></div><div><span><PackageCheck /> Opening dimensions</span><span><PackageCheck /> Product or application</span><span><PackageCheck /> Quantity and location</span><span><PackageCheck /> Drawings or photos</span></div><Link className="reference-button reference-button--red" href="/contact">Send requirements <ArrowRight size={18} /></Link></div></div></section>
    <ClientLogos />
    <section className="reference-final"><div className="container"><div><p className="reference-eyebrow">Project consultation</p><h2>Prepare the Right Door for Your Facility.</h2><p>Share your project requirements and our team will help define the next step.</p></div><Link className="reference-button reference-button--white" href="/contact">Start your project <ArrowRight size={18} /></Link></div></section>
  </div>;
}
