import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Factory, Gauge, Layers3, Maximize2, MessageCircle, PackageCheck, Radio, Settings2, ShieldCheck, Wind, Zap } from "lucide-react";
import { Breadcrumb } from "@/components/breadcrumb";

export const metadata: Metadata = { title: "High Speed Roll Up Door", description: "PVC high speed roll up door for frequent industrial traffic, with configurable activation, safety and control options.", alternates: { canonical: "/products/high-speed-roll-up-door" } };
const parameters = [["Opening speed","0.6–1.5 m/s"],["Maximum size","5,800 × 6,000 mm"],["Curtain","0.8 mm PVC; 1.2 mm clear vision panel"],["Wind resistance","Grade 6–8 with aluminium wind bars"],["Control system","FROG PUPIL variable-frequency control"],["Safety","Autonics infrared photocell"],["Power supply","220 V standard"],["Motor power","0.75 / 1.5 / 2.2 kW by door area"],["Frame finish","Painted cold-rolled steel, RAL 7035"],["Motor position","Left or right"],["Headroom","500 mm"],["Side room","150 mm non-motor side; 400 mm motor side"]];
const uses = ["Manufacturing lines","Logistics passages","Food processing","Clean production areas"];
const applicationCases = [
  { image: "/images/factory-doors.jpg", number: "01", title: "Automated Manufacturing Line", text: "Rapid separation helps production equipment, operators and material flow move through high-frequency internal openings." },
  { image: "/images/logistics-door.jpg", number: "02", title: "Warehouse & Logistics Passage", text: "Fast opening and configurable activation support forklifts, carts and repeated goods movement between warehouse zones." },
  { image: "/images/cleanroom-door.jpg", number: "03", title: "Clean Production Area", text: "A flexible PVC curtain and perimeter sealing help manage dust, insects and uncontrolled air exchange between work areas." },
];
const relatedProducts = [
  { href: "/products/high-speed-roll-up-door", image: "/images/catalog-high-speed-roll-up.webp", category: "High Speed Doors", title: "High Speed Roll Up Door", text: "Flexible PVC rapid access for frequent internal traffic." },
  { href: "/products/high-speed-spiral-door", image: "/images/catalog-high-speed-spiral.webp", category: "High Speed Doors", title: "High Speed Spiral Door", text: "Rigid insulated slats for fast, secure exterior openings." },
  { href: "/products/industrial-sectional-door", image: "/images/catalog-sectional-door.webp", category: "Sectional Doors", title: "Industrial Sectional Door", text: "Insulated vertical access for factories and warehouses." },
  { href: "/products/hydraulic-dock-leveler", image: "/images/catalog-dock-leveler.webp", category: "Loading Dock Equipment", title: "Hydraulic Dock Leveler", text: "A dependable bridge between loading bays and vehicles." },
];
const productDetails = [
  { image: "/images/rapid-door-control-system.jpg", title: "Visual Servo Control System", text: "The controller combines a clear operating display, status feedback, parameter adjustment and an emergency-stop function in one protected enclosure." },
  { image: "/images/rapid-door-pvc-curtain.jpg", title: "High-Strength PVC Curtain", text: "Wear-resistant PVC fabric provides a flexible separation surface with solid colours and transparent vision sections available for the application." },
  { image: "/images/rapid-door-sealing-brush.jpg", title: "Dense Nylon Side Brushes", text: "Closely arranged nylon brushes guide the curtain while helping reduce dust, insects and uncontrolled air exchange around the side tracks." },
  { image: "/images/rapid-door-safety-photocell.jpg", title: "Infrared Safety Photocell", text: "The protected photocell monitors the passage and sends a safety signal when a person, vehicle or object is detected in the doorway." },
  { image: "/images/rapid-door-laser-frame.jpg", title: "Precision-Formed Frame", text: "Laser-cut and formed steel components improve dimensional consistency, simplify assembly and support dependable long-term operation." },
  { image: "/images/rapid-door-wind-bar.jpg", title: "Aluminium Wind-Resistance Bar", text: "High-strength aluminium profiles reinforce the flexible curtain and help the door remain stable under the specified operating conditions." },
];

export default function HighSpeedRollUpDoorPage(){return <div className="product-page">
<section className="product-page__hero"><Image src="/images/hero-industrial-door.jpg" alt="High speed roll up door installed at an industrial passage" fill priority sizes="100vw" className="product-page__hero-image"/><div className="product-page__hero-shade"/><div className="container product-page__hero-inner"><div className="product-page__hero-copy"><p className="reference-eyebrow">High Speed Doors · PVC Series</p><h1>High Speed Roll Up Door</h1><p>Explore a rapid PVC door system by opening size, traffic frequency, environmental separation, activation method and control interface.</p><div className="reference-actions"><Link className="reference-button reference-button--red" href="/contact">Discuss Your Rapid Door <ArrowRight size={18}/></Link><a className="reference-button reference-button--ghost" href="#technical-data">Explore Parameters</a></div></div><div className="product-page__hero-facts"><div><Gauge/><span>Opening speed</span><strong>Up to 1.5 m/s</strong></div><div><Maximize2/><span>Maximum size</span><strong>5.8 × 6.0 m</strong></div><div><ShieldCheck/><span>Certification</span><strong>CE certified</strong></div></div></div></section>
<Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Products", href: "/products" }, { label: "High Speed Roll Up Door" }]} />
<section className="product-page__intro"><div className="container product-page__intro-grid"><div className="product-page__intro-image"><Image src="/images/high-speed-roll-up-door-product.jpg" alt="Blue PVC high speed roll up door with a transparent vision panel" fill sizes="(min-width: 900px) 50vw, 100vw"/></div><div className="product-page__intro-copy"><p className="reference-eyebrow blue">Built for daily flow</p><h2>Speed Where the Process Needs It</h2><strong>A practical rapid door for interior production and logistics openings.</strong><p>The flexible PVC curtain, variable-frequency drive and configurable activation methods support repeated cycles while brush seals and a U-shaped bottom pocket help limit dust, insects and air exchange.</p><Link className="reference-text-link" href="#technical-data">Review technical data <ArrowRight size={17}/></Link></div></div><div className="container product-page__benefits"><article><Zap/><b>01</b><h3>Fast Cycling</h3><p>0.6–1.5 m/s opening speed helps reduce waiting at busy passages.</p></article><article><Layers3/><b>02</b><h3>Flexible Separation</h3><p>PVC curtain options include solid, transparent, mesh and ventilated finishes.</p></article><article><ShieldCheck/><b>03</b><h3>Safer Movement</h3><p>Infrared photocell protection monitors the doorway during operation.</p></article><article><Radio/><b>04</b><h3>Ready to Integrate</h3><p>Standard button control with reserved I/O terminals and RS-485 communication.</p></article></div></section>
<section className="product-page__details"><div className="container"><div className="product-page__center-head"><p className="reference-eyebrow blue">Product details</p><h2>Engineered in Every Component</h2><p>Key parts are selected and assembled as one coordinated rapid-door system for stable movement, sealing and safe daily operation.</p></div><div className="product-page__detail-grid">{productDetails.map((detail,index)=><article key={detail.title}><div className="product-page__detail-image"><Image src={detail.image} alt={detail.title} fill sizes="(min-width: 1000px) 33vw, (min-width: 650px) 50vw, 100vw"/></div><div className="product-page__detail-copy"><span>0{index+1}</span><h3>{detail.title}</h3><p>{detail.text}</p></div></article>)}</div></div></section>
<section className="product-page__principle"><div className="container"><div className="product-page__center-head"><p className="reference-eyebrow blue">Working principle</p><h2>How the Rapid Door Operates</h2><p>The activation device, controller, motor, curtain and safety sensors work together as one coordinated entrance system.</p></div><div className="product-page__steps"><article><span>01</span><Radio/><h3>Detect</h3><p>A radar, button, pull cord or equipment signal sends an opening request.</p></article><article><span>02</span><Zap/><h3>Open Fast</h3><p>The variable-frequency drive lifts the PVC curtain at a controlled rapid speed.</p></article><article><span>03</span><ShieldCheck/><h3>Protect</h3><p>The infrared photocell monitors the passage while traffic moves through.</p></article><article><span>04</span><Layers3/><h3>Close & Seal</h3><p>The curtain returns to its closed position to restore separation.</p></article></div></div></section>
<section className="product-page__planning"><div className="container product-page__planning-grid"><div><p className="reference-eyebrow blue">Project planning</p><h2>Conditions to Confirm Before Selection</h2><p>A reliable configuration starts with verified site conditions, not only the product name.</p></div><dl><div><dt>Finished opening</dt><dd>Width, height and surrounding construction</dd></div><div><dt>Traffic pattern</dt><dd>Pedestrians, forklifts, AGVs or equipment</dd></div><div><dt>Operating frequency</dt><dd>Expected cycles per hour and per day</dd></div><div><dt>Environment</dt><dd>Dust, insects, temperature, wind and pressure</dd></div><div><dt>Activation</dt><dd>Button, radar, pull cord or automatic signal</dd></div><div><dt>Control interface</dt><dd>I/O terminals, RS-485 and access control</dd></div></dl></div></section>
<section className="product-page__specs" id="technical-data"><div className="container product-page__spec-grid"><div className="product-page__spec-copy"><p className="reference-eyebrow">System and parameters</p><h2>Standard Configuration</h2><p>Confirm whether the project requires a complete door, selected controls or a customized interface. The final proposal defines every inclusion.</p><ul><li><Check/> Made-to-measure production</li><li><Check/> Left- or right-hand motor layout</li><li><Check/> Multiple curtain colours available</li><li><Check/> Remote installation guidance</li></ul></div><div><h3 className="product-page__table-title">Concise Parameter Reference</h3><dl className="product-page__parameter-list">{parameters.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="product-page__spec-note">Final size, motor power, operating speed, wind resistance and control functions must be confirmed against the opening and operating environment.</p></div></div></section>
<section className="product-page__cases"><div className="container"><div className="reference-split-heading"><div><p className="reference-eyebrow blue">Application examples</p><h2>High Speed Door Use Cases</h2></div><div className="reference-copy"><strong>See how rapid doors support different industrial workflows.</strong><p>These examples illustrate common application directions. Final configuration still depends on the verified opening, traffic pattern and environmental requirements.</p></div></div><div className="product-page__case-grid">{applicationCases.map(item=><article key={item.title}><div className="product-page__case-image"><Image src={item.image} alt={item.title} fill sizes="(min-width: 900px) 33vw, 100vw"/></div><div className="product-page__case-copy"><span>{item.number}</span><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div></div></section>
<section className="product-page__applications"><div className="container"><div className="reference-split-heading"><div><p className="reference-eyebrow blue">Typical applications</p><h2>One Door, Multiple Workflows</h2></div><div className="reference-copy"><strong>Best suited to frequent internal traffic and controlled separation.</strong><p>Activation can be configured around people, forklifts, AGVs or process equipment.</p></div></div><div className="product-page__application-grid">{uses.map((item,index)=><article key={item}><span>0{index+1}</span><Wind/><h3>{item}</h3><p>Configure the curtain, sensor and opening method around the traffic pattern and environmental requirement.</p></article>)}</div></div></section>
<section className="product-page__related"><div className="container"><div className="product-page__related-head"><div><p className="reference-eyebrow blue">Product recommendations</p><h2>Explore More Industrial Door Systems</h2></div><Link className="reference-text-link" href="/products">View all products <ArrowRight size={17}/></Link></div><div className="product-page__related-grid">{relatedProducts.map(product=><Link className="product-page__related-card" href={product.href} key={product.href}><div className="product-page__related-image"><Image src={product.image} alt={product.title} fill unoptimized sizes="(min-width: 1100px) 25vw, (min-width: 650px) 50vw, 100vw"/></div><div className="product-page__related-copy"><span>{product.category}</span><h3>{product.title}</h3><p>{product.text}</p><em>View product <ArrowRight size={16}/></em></div></Link>)}</div></div></section>
<section className="product-page__support"><div className="container product-page__support-grid"><div className="product-page__support-image"><Image src="/images/factory-building.jpg" alt="SEPPES industrial door manufacturing facility" fill sizes="(min-width: 900px) 50vw, 100vw"/></div><div><p className="reference-eyebrow">Manufacturing and support</p><h2>From Configuration to Export Delivery</h2><p>SEPPES coordinates opening review, customized production, inspection, packaging, technical documents and remote support for global industrial projects.</p><div className="product-page__support-list"><span><Settings2/>Custom engineering and OEM/ODM</span><span><Factory/>Manufacturing and quality inspection</span><span><PackageCheck/>Export packaging and spare parts</span><span><MessageCircle/>Remote installation support</span></div></div></div></section>
<section className="product-page__faq"><div className="container"><div className="product-page__center-head"><p className="reference-eyebrow blue">FAQ</p><h2>High Speed Roll Up Door Questions</h2><p>Use these answers for early planning, then confirm the final configuration in the project proposal.</p></div><div className="product-page__faq-list"><details><summary>What information is needed for a quotation?</summary><p>Send the finished opening width and height, quantity, application, traffic type, operating frequency, project location and available photos.</p></details><details><summary>Can the door size and curtain colour be customized?</summary><p>Yes. Door dimensions are made to measure, and multiple solid, transparent, mesh and ventilated curtain options are available.</p></details><details><summary>Can the door connect with an AGV or production line?</summary><p>Yes. The standard control design reserves I/O terminals and RS-485 communication for agreed automation interfaces.</p></details><details><summary>What safety protection is included?</summary><p>The standard reference configuration includes an infrared photocell. Additional devices can be reviewed for the application.</p></details></div></div></section>
<section className="product-page__project-cta"><div className="container"><div><p className="reference-eyebrow">Project consultation</p><h2>Send Us Your Opening Details.</h2><p>Share the width, height, quantity, application, project location and available photos or drawings.</p></div><Link className="reference-button reference-button--white" href="/contact">Get a Configuration <ArrowRight size={18}/></Link></div></section>
</div>}
