import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Bot, Check, Factory, PackageCheck, ShieldCheck, Snowflake, Sparkles, ThermometerSnowflake, Truck, Utensils } from "lucide-react";
import { CTA } from "@/components/cta";
import { Breadcrumb } from "@/components/breadcrumb";

export const metadata = { title: "Industrial Door Solutions", description: "Industrial door solutions for logistics, clean rooms, cold storage, food processing, automotive and smart manufacturing facilities." };

const solutions = [
  {number:"01",title:"Logistics & Warehousing",description:"Keep busy loading bays moving while protecting people, goods and building temperature.",image:"/images/logistics-door.jpg",icon:Truck,points:["Fast vehicle flow","Dock safety","Weather sealing"]},
  {number:"02",title:"Clean Rooms",description:"Control particles, pressure and cross-contamination across sensitive production zones.",image:"/images/cleanroom-door.jpg",icon:Sparkles,points:["Tight perimeter seal","Easy-clean surfaces","Interlock control"]},
  {number:"03",title:"Cold Chain",description:"Reduce cold-air loss and condensation without slowing high-frequency material movement.",image:"/images/high-speed-roll-up-door-product.jpg",icon:Snowflake,points:["Thermal separation","Rapid cycling","Anti-freeze options"]},
  {number:"04",title:"Food & Beverage",description:"Support hygiene programs and efficient traffic between processing, packing and storage areas.",image:"/images/factory-doors.jpg",icon:Utensils,points:["Hygienic construction","Pest control","Washdown options"]},
  {number:"05",title:"Automotive",description:"Coordinate doors with production lines, forklifts and robot cells for uninterrupted output.",image:"/images/factory-building.jpg",icon:Factory,points:["High-cycle operation","Zone separation","Safety sensing"]},
  {number:"06",title:"Smart Manufacturing",description:"Connect industrial access points to AGVs, conveyors and facility control systems.",image:"/images/hero-industrial-door.jpg",icon:Bot,points:["AGV integration","Remote I/O","Custom logic"]},
];
const priorities=[{icon:Truck,title:"Traffic flow",text:"Opening speed, vehicle type and daily cycles define the operating system."},{icon:ThermometerSnowflake,title:"Environment",text:"Temperature, wind, hygiene and pressure determine curtain and sealing choices."},{icon:ShieldCheck,title:"Safety",text:"Photo eyes, safety edges and traffic controls protect every shared opening."},{icon:Bot,title:"Automation",text:"Radar, loops, remote signals and AGV controls fit your workflow."}];

export default function SolutionsPage(){return <div className="solutions-page">
  <section className="solutions-hero"><Image src="/images/factory-doors.jpg" alt="Industrial doors inside a modern production facility" fill priority sizes="100vw"/><div className="solutions-hero__overlay"/><div className="container solutions-hero__content"><p className="solutions-kicker">Application solutions</p><h1>The right door starts with your operating environment.</h1><p>From cold storage to automated production, SEPPES configures every access point around traffic, safety, sealing and control requirements.</p><div className="solutions-actions"><Link className="solutions-button solutions-button--red" href="#industries">Explore industries <ArrowRight size={17}/></Link><Link className="solutions-button solutions-button--ghost" href="/contact">Talk to an engineer</Link></div></div><div className="solutions-hero__tag"><span>90+</span> countries and regions served</div></section>
  <Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Solutions" }]} />
  <section className="solutions-intro"><div className="container solutions-intro__grid"><div><p className="solutions-kicker solutions-kicker--blue">Designed around the application</p><h2>Industrial doors are part of the workflow—not just an opening.</h2></div><div><p className="solutions-intro__lead">The best solution balances movement, environmental control and risk. We translate real site conditions into a complete door specification.</p><p>Share your opening sizes, traffic patterns and operating challenges. Our engineers recommend the door type, controls and safety package that fit the project.</p></div></div><div className="container solutions-priority-grid">{priorities.map(({icon:Icon,title,text},index)=><article key={title}><span>0{index+1}</span><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="solutions-industries" id="industries"><div className="container"><div className="solutions-section-head"><div><p className="solutions-kicker solutions-kicker--blue">Industry expertise</p><h2>Find a solution for your facility.</h2></div><p>Each environment has different demands. Start with your industry to see the performance priorities we design around.</p></div><div className="solutions-grid">{solutions.map(({number,title,description,image,icon:Icon,points})=><article className="solution-card" key={title}><div className="solution-card__image"><Image src={image} alt={`${title} industrial door application`} fill sizes="(max-width: 760px) 100vw, 50vw"/><span>{number}</span></div><div className="solution-card__body"><div className="solution-card__title"><Icon/><h3>{title}</h3></div><p>{description}</p><ul>{points.map(point=><li key={point}><Check size={15}/>{point}</li>)}</ul><Link href="/contact">Discuss your application <ArrowRight size={16}/></Link></div></article>)}</div></div></section>
  <section className="solutions-process"><div className="container solutions-process__grid"><div className="solutions-process__copy"><p className="solutions-kicker">Project pathway</p><h2>From site conditions to a ready-to-install system.</h2><p>A clear four-stage process keeps product selection, customization and delivery aligned from the first conversation.</p><Link className="solutions-button solutions-button--red" href="/contact">Start your project <ArrowRight size={17}/></Link></div><ol><li><b>01</b><div><h3>Define the opening</h3><p>Dimensions, location, traffic, environment and project country.</p></div></li><li><b>02</b><div><h3>Engineer the solution</h3><p>Door model, structure, activation, controls and safety package.</p></div></li><li><b>03</b><div><h3>Confirm & manufacture</h3><p>Technical drawings and project details are approved before production.</p></div></li><li><b>04</b><div><h3>Deliver with support</h3><p>Export packing, documentation and installation guidance for your team.</p></div></li></ol></div></section>
  <section className="solutions-fit"><div className="container solutions-fit__inner"><PackageCheck/><div><p className="solutions-kicker solutions-kicker--blue">Not sure where to start?</p><h2>Send us four project details.</h2><p>Opening size, application, quantity and project country are enough for our team to begin.</p></div><Link className="solutions-button solutions-button--blue" href="/contact">Get a recommendation <ArrowRight size={17}/></Link></div></section><CTA/>
</div>}
